### ISSUE TITLE
Determine why upgrading to Android Gradle Plugin version 3.2.0 prevents build from working

### ISSUE THREAD

**Issue by samarthd** [samarthd/FutureMessengerApp#108]
Upgraded to it and got error like this:

```
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':app:transformClassesWithDexBuilderForDebug'
...
.RuntimeException: java.lang.RuntimeException
    at com.android.builder.profile.Recorder$Block.handleException(Recorder.java:55)
    at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:104)
    at com.android.build.gradle.internal.pipeline.TransformTask.transform(TransformTask.java:230)
... 33 more

Caused by: com.android.build.api.transform.TransformException: java.lang.RuntimeException: java.lang.RuntimeException
    at com.android.build.gradle.internal.transforms.DexArchiveBuilderTransform.transform(DexArchiveBuilderTransform.java:427)
    at com.android.build.gradle.internal.pipeline.TransformTask$2.call(TransformTask.java:239)
    at com.android.build.gradle.internal.pipeline.TransformTask$2.call(TransformTask.java:235)
    at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:102)
    ... 49 more
    at com.android.ide.common.internal.WaitableExecutor.waitForTasksWithQuickFail(WaitableExecutor.java:146)
    at com.android.build.gradle.internal.transforms.DesugarIncrementalTransformHelper.getInitalGraphData(DesugarIncrementalTransformHelper.java:162)
    at com.android.build.gradle.internal.transforms.DesugarIncrementalTransformHelper.makeDesugaringGraph(DesugarIncrementalTransformHelper.java:130)
    at com.google.common.base.Suppliers$NonSerializableMemoizingSupplier.get(Suppliers.java:160)
    at com.android.build.gradle.internal.transforms.DesugarIncrementalTransformHelper.getDependenciesPaths(DesugarIncrementalTransformHelper.java:231)
    at com.android.build.gradle.internal.transforms.DexArchiveBuilderTransform.getD8DesugaringCacheInfo(DexArchiveBuilderTransform.java:461)
    at com.android.build.gradle.internal.transforms.DexArchiveBuilderTransform.transform(DexArchiveBuilderTransform.java:375)

```

It is unclear what exactly is producing this error, but it seems likely that it's related to the **"Desugaring with D8 is now enabled by default."** change mentioned here: https://developer.android.com/studio/releases/gradle-plugin

Downgrading to 3.1.0 "fixes" it, but I think I will still get the issue where I have to clean and rebuild each time I want to deploy changes to the emulator or a testing device.

**Comment by samarthd** [comment]
**Note:** putting `android.enableD8.desugaring=false` in `gradle.properties` after upgrading to 3.2.0 fixed the issue...but I don't like that I have to do that.

**Comment by samarthd** [comment]
https://github.com/rzwitserloot/lombok/issues/1882#issuecomment-427550826
